version: '3'
services:
  web:
    build: .
    ports:
      - "5005:5000"
    volumes:
      - .:/app
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/posgresql/data
volumes:
  postgres_data: